### ISSUE TITLE
Builder setShapeType

### ISSUE THREAD

**Issue by Angelk90** [IvBaranov/MaterialLetterIcon#13]
@IvBaranov : Hi, congratulations for the module.

I was trying it but when I try to set setShapeType I can not.

I tried with `MaterialLetterIcon.Shape.CIRCLE`, but it does not recognize it.

How can I do?

code:
```

 new MaterialLetterIcon.Builder(reactContext)
                .shapeColor(Color.parseColor("#000000"))
                .setShapeType(MaterialLetterIcon.Shape.CIRCLE)
                .letter("S")
                .letterColor(Color.parseColor("#000000"))
                .letterSize(26)
                .lettersNumber(1)
                .letterTypeface(font)
                .initials(false)
                .initialsNumber(2)
                .create();
```

**Comment by IvBaranov** [comment]
There is an error in README, consider using `shapeType()` method rather than `setShapeType()`.

**Comment by Angelk90** [comment]
@IvBaranov : ok, one last thing, you have to declare this in the xml file, to be able to use the module or through Builder to method create ().

```
<com.github.ivbaranov.mli.MaterialLetterIcon
    android:layout_width="@dimen/letter_icon_size"
    android:layout_height="@dimen/letter_icon_size" />
```

**Comment by IvBaranov** [comment]
You can add `MaterialLetterIcon` either by declaring it in xml or by adding view programmatically using builder.

**Comment by Angelk90** [comment]
@IvBaranov : I have developed a bridge of your react-native module, can I refer to the profile of your module as a reference?

**Comment by Angelk90** [comment]
@IvBaranov :  There is a way to contact you privately?

**Comment by IvBaranov** [comment]
@Angelk90 [@0ff5pring](https://twitter.com/0ff5pring) would be ok.

**Comment by Angelk90** [comment]
@IvBaranov :  In your account on Twitter does not allow you to send private messages.

**Comment by IvBaranov** [comment]
@Angelk90 sorry, fixed.
